In [1]:
#import necessary libraries
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns

In [3]:
#reading csv file
df=pd.read_csv(r"C:\Users\User\Desktop\Codsoft\creditcard.csv")
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [4]:
#finding shape 
df.shape

(284807, 31)

In [5]:
#finding size
df.size

8829017

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
Time      284807 non-null float64
V1        284807 non-null float64
V2        284807 non-null float64
V3        284807 non-null float64
V4        284807 non-null float64
V5        284807 non-null float64
V6        284807 non-null float64
V7        284807 non-null float64
V8        284807 non-null float64
V9        284807 non-null float64
V10       284807 non-null float64
V11       284807 non-null float64
V12       284807 non-null float64
V13       284807 non-null float64
V14       284807 non-null float64
V15       284807 non-null float64
V16       284807 non-null float64
V17       284807 non-null float64
V18       284807 non-null float64
V19       284807 non-null float64
V20       284807 non-null float64
V21       284807 non-null float64
V22       284807 non-null float64
V23       284807 non-null float64
V24       284807 non-null float64
V25       284807 non-null float64
V26       284807 non-null float64
V27       284807 non-null float64
V28       284807 non-null float64
Amount    284807 non-null float64
Class     284807 non-null int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [7]:
#statistics
df.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,...,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.000000
mean,94813.859575,3.919560e-15,5.688174e-16,-8.769071e-15,2.782312e-15,-1.552563e-15,2.010663e-15,-1.694249e-15,-1.927028e-16,-3.137024e-15,...,1.537294e-16,7.959909e-16,5.367590e-16,4.458112e-15,1.453003e-15,1.699104e-15,-3.660161e-16,-1.206049e-16,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,...,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,...,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.000000
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,...,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.000000
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,...,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000

In [8]:
#identifying null values
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [9]:
#finding number of values present in class column
df["Class"].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [10]:
#classifying normal and fraud transactions
normal_trans=df[df['Class']==0]
fraud_trans=df[df['Class']==1]

In [11]:
print(normal_trans.shape)
print(fraud_trans.shape)

(284315, 31)
(492, 31)

In [12]:
normal_trans['Amount'].describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [13]:
fraud_trans['Amount'].describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [25]:
#comaring the values for both transactions
df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [26]:
#building a sample dataset containing similar distribution of normal and fraud transactions
normal_sample=normal_trans.sample(n=492)

In [32]:
df1=pd.concat([normal_sample,fraud_trans],axis=0)

In [33]:
df1.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
3333,2880.0,1.253551,0.224565,0.286665,0.449085,-0.008004,-0.226442,0.005006,-0.061897,0.003723,...,-0.257439,-0.682704,0.099131,-0.418417,0.227380,0.153671,-0.010031,0.011484,1.29,0
160382,113313.0,-2.714436,3.044536,-3.305199,-1.406683,-0.145586,-1.043348,-0.347337,1.959858,-0.585882,...,0.370652,0.744213,0.061540,0.239676,0.026430,0.087697,0.046768,0.184859,0.77,0
70013,53672.0,-0.385109,1.137025,1.301256,0.069402,0.121756,-0.964708,0.797031,-0.132699,-0.553466,...,-0.242003,-0.607338,0.007058,0.361068,-0.119296,0.068027,0.247068,0.102098,14.78,0
90116,62870.0,1.104167,-0.890917,-0.548597,-0.859893,1.243432,3.902582,-1.122172,1.032397,1.065743,...,-0.236271,-0.762969,-0.029448,1.081649,0.264313,0.948868,-0.047364,0.022200,92.75,0
170187,120061.0,2.183153,-1.696814,0.125714,-1.382981,-2.111803,-0.405371,-1.799098,0.014698,-0.539516,...,-0.128197,0.155720,0.339380,-0.045770,-0.574834,-0.244093,0.065521,-0.027012,34.00,0

In [34]:
df1["Class"].value_counts()

1    492
0    492
Name: Class, dtype: int64

In [35]:
df1.groupby(["Class"]).mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94205.922764,0.032155,0.055985,0.109882,-0.039812,0.043521,-0.048562,0.066369,0.029259,-0.034919,...,-0.044784,0.026509,0.001812,-0.007753,-0.009209,0.008705,0.002540,0.001924,0.011390,79.475772
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [36]:
x=df1.drop(['Class'],axis=1)
y=df1['Class']
print(x)
print(y)

            Time        V1        V2        V3        V4        V5        V6  \
3333      2880.0  1.253551  0.224565  0.286665  0.449085 -0.008004 -0.226442
160382  113313.0 -2.714436  3.044536 -3.305199 -1.406683 -0.145586 -1.043348
70013    53672.0 -0.385109  1.137025  1.301256  0.069402  0.121756 -0.964708
90116    62870.0  1.104167 -0.890917 -0.548597 -0.859893  1.243432  3.902582
170187  120061.0  2.183153 -1.696814  0.125714 -1.382981 -2.111803 -0.405371
203052  134622.0 -0.365124  1.036996 -0.315456 -0.887105  1.214019 -0.377210
91339    63422.0 -0.732989  0.761198  0.663779  0.630345 -0.605200 -1.381321
14249    25307.0  0.953499 -0.959851  1.234708  0.917049 -1.773495 -0.386326
265572  161945.0 -0.606711  0.462034  1.479819 -0.778672  0.482460  1.107675
198655  132591.0 -0.564306 -0.216545  0.206509 -0.946398  0.938396  1.957638
252116  155659.0  2.079214 -0.050268 -1.423316  0.260284  0.315353 -0.698692
284432  172435.0  2.020989  0.706524 -2.841595  0.812181  0.836207 -2.021954
283756  171850.0  0.750809  0.393628 -0.491441 -0.673725  0.684186  0.006524
164240  116566.0  1.701889 -1.449469 -0.872815 -1.901250 -1.326821 -1.095405
248204  153837.0  0.019677  0.798404  0.146139 -0.802330  0.693872 -0.485983
238656  149760.0 -1.108307  1.676979 -0.564841 -0.955476  0.533045 -0.565562
132548   80025.0  1.395728 -0.901571  0.974208 -0.797000 -1.488472 -0.080689
77803    57215.0  1.150699 -0.219620  1.156848  0.459191 -1.219048 -0.800929
113173   72964.0  1.319883 -0.750097  0.873443 -0.749860 -1.040546  0.411615
281003  169873.0  0.322698  0.972182 -0.349555 -0.034990  0.648050 -1.186074
2562      2106.0 -0.381266  0.715988  1.237381 -1.956540  0.005965 -1.693550
63630    50807.0 -1.490492  1.748116  1.172497  1.546853  0.300819  0.590790
94038    64703.0  0.281063 -1.967230  0.371764 -0.316058 -1.742066 -0.634351
203758  134953.0  2.134106  0.070667 -2.304984  0.040547  1.051336 -0.477026
122123   76444.0 -1.135568  0.989345  2.329934 -0.205425 -0.005689 -0.104936
205169  135621.0  2.059117  0.167670 -1.767548  0.384603  0.549912 -0.767351
108628   70997.0 -2.129024  1.694985  1.021626  0.399145 -0.663135 -0.106473
137972   82420.0  0.935055 -1.914651  0.512082 -1.248447 -1.891783 -0.179141
268741  163362.0 -1.353844  2.182292 -1.449940 -1.328877  0.734247 -1.756153
96805    65945.0 -0.540595  0.826453  1.140816  0.072024 -0.024853 -0.377536
...          ...       ...       ...       ...       ...       ...       ...
251891  155548.0  1.878230  1.325630 -2.333469  4.233151  1.355184 -0.853508
251904  155554.0 -1.040067  3.106703 -5.409027  3.109903 -0.887237 -2.497522
252124  155662.0 -1.928613  4.601506 -7.124053  5.716088  1.026579 -3.189073
252774  155965.0 -1.201398  4.864535 -8.328823  7.652399 -0.167445 -2.767695
254344  156685.0 -0.129778  0.141547 -0.894702 -0.457662  0.810608 -0.504723
254395  156710.0  0.202402  1.176270  0.346379  2.882138  1.407133 -0.504355
255403  157207.0  1.170756  2.501038 -4.986159  5.374160  0.997798 -1.259004
255556  157284.0 -0.242245  4.147186 -5.672349  6.493741  1.591168 -1.602523
258403  158638.0 -5.976119 -7.196980 -5.388316  5.104799  4.676533 -5.566870
261056  159844.0 -0.408111  3.132944 -3.098030  5.803893  0.890609 -0.501474
261473  160034.0 -2.349340  1.512604 -2.647497  1.753792  0.406328 -2.188494
261925  160243.0 -2.783865  1.596824 -2.084844  2.512986 -1.446749 -0.828496
262560  160537.0  0.567539  3.309385 -6.631268  6.394574 -0.054172 -2.396535
262826  160665.0 -0.417340  4.700055 -7.521767  7.671884  0.260821 -2.646693
263080  160791.0  2.132386  0.705608 -3.530759  0.514779  1.527175 -1.716268
263274  160870.0 -0.644278  5.002352 -8.252739  7.756915 -0.216267 -2.751496
263324  160895.0 -0.848290  2.719882 -6.199070  3.044437 -3.301910 -1.992117
263877  161154.0 -3.387601  3.977881 -6.978585  1.657766 -1.100500 -3.599487
268375  163181.0 -5.238808  0.623013 -5.784507  1.678889 -0.364432 -0.477295
272521  165132.0 -7.503926 -0.360628 -3.830952  2.486103  2.497367  1.332437
274382  165981.0 -5.766879 -8.402154  0.056543  6.950983  9.880564 -5.773192
274475  166028.0 -0.956390  2.361594 -3.171195  1.970759  0.474761 -1.902598
275992  166831.0 -2.027135 -1.131890 -1.135194  1.086963 -0.010547  0.423797
276071  166883.0  2.091900 -0.757459 -1.192258 -0.755458 -0.620324 -0.322077
276864  167338.0 -1.374424  2.793185 -4.346572  2.400731 -1.688433  0.111136
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7         V8        V9  ...       V20       V21       V22  \
3333    0.005006  -0.061897  0.003723  ... -0.079507 -0.257439 -0.682704
160382 -0.347337   1.959858 -0.585882  ... -0.116362  0.370652  0.744213
70013   0.797031  -0.132699 -0.553466  ...  0.214987 -0.242003 -0.607338
90116  -1.122172   1.032397  1.065743  ...  0.216848 -0.236271 -0.762969
170187 -1.799098   0.014698 -0.539516  ... -0.400390 -0.128197  0.155720
203052  0.895837   0.112819 -0.432976  ...  0.024872  0.216184  0.657099
91339  -0.120048   0.396859  0.015235  ... -0.191926 -0.065165 -0.351385
14249  -0.750999   0.016312 -0.338962  ... -0.268308 -0.277557 -0.562339
265572  0.087144   0.498326  0.373058  ... -0.010678  0.293700  1.234375
198655 -0.122514   0.628787  0.690293  ... -0.394606  0.439241  1.444053
252116  0.232069  -0.278126  0.764511  ... -0.206092 -0.293797 -0.676728
284432  0.725502  -0.510672  0.450757  ... -0.119204 -0.063240  0.024090
283756  0.143447  -0.835620  0.008850  ... -0.336762  0.436229 -1.200900
164240 -0.516572  -0.064997  2.490728  ...  0.069514  0.385103  0.934728
248204  0.890971  -0.012015 -0.285984  ... -0.016765 -0.228332 -0.504671
238656  0.618204   0.426183 -0.163682  ...  0.031105 -0.269722 -0.632553
132548 -1.415380   0.159454  0.071013  ...  0.062326  0.370516  0.961821
77803  -0.406218  -0.129495  0.685485  ...  0.033253  0.097318  0.512110
113173 -1.182465   0.229070 -0.531075  ...  0.091007  0.401134  1.294963
281003  1.031063  -0.239443  0.051743  ... -0.143789 -0.210621 -0.477686
2562    1.175983  -0.459971  0.822233  ...  0.014847  0.081084  0.608915
63630   0.516321   0.484971 -1.174975  ... -0.354650 -0.087942 -0.688767
94038   0.050550  -0.143349  1.813810  ...  0.877712  0.304282 -0.015233
203758  0.579134  -0.309970 -0.152660  ... -0.149330  0.108833  0.485025
122123  0.501967  -0.067408  0.093019  ...  0.281425 -0.132502 -0.024966
205169  0.256202  -0.276380  0.380134  ... -0.069894 -0.356941 -0.914482
108628 -0.233594   0.513452  0.190807  ... -0.260698  0.145548  0.154983
137972 -0.993507   0.083382 -1.909844  ...  0.082494 -0.140179 -0.645869
268741  1.509215  -0.219367  0.519173  ...  0.531590  0.093149  0.849470
96805   0.935324   0.037181 -0.434171  ...  0.281561 -0.182315 -0.581231
...          ...        ...       ...  ...       ...       ...       ...
251891  0.716025  -0.164910 -1.502345  ... -0.226108 -0.152131 -0.360736
251904 -2.073347   0.639818 -3.013331  ...  1.054390  0.773961  0.214868
252124 -2.261897   1.185096 -4.441942  ...  0.328796  0.602291 -0.541287
252774 -3.176421   1.623279 -4.367228  ...  0.597026  0.532320 -0.556913
254344  1.373588  -0.209476  0.208494  ...  0.399447 -0.032643 -0.246526
254395  1.438537  -0.395603 -1.555142  ... -0.206239  0.242560  0.841230
255403 -1.237689   0.358426 -2.612489  ...  0.227618  0.123145 -0.713201
255556 -0.950463   0.722903 -4.128505  ...  0.562030  0.249023 -0.480286
258403 -4.291180   0.876531 -1.075478  ...  3.136338  1.459369 -0.136262
261056 -0.440054   0.591828 -3.267693  ...  0.499568  0.098482 -0.538375
261473 -0.686935  -0.547984 -0.099528  ... -0.093421 -0.088519 -0.595178
261925 -0.732262  -0.203329 -0.347046  ... -0.515001  0.203563  0.293268
262560 -2.792489   0.514811 -3.541780  ...  0.555412  0.614221 -0.365047
262826 -2.854432   0.958783 -4.588536  ...  0.832035  0.622200 -0.437708
263080  1.132791  -0.574214  0.128904  ... -0.211167  0.163739  0.703910
263274 -3.358857   1.406268 -4.403852  ...  0.816558  0.587728 -0.605759
263324 -3.734902   1.520079 -2.548788  ...  0.319576  1.125229  0.805258
263877 -3.686651   1.942252 -3.065089  ... -0.004301  1.043587  0.262189
268375 -4.276132  -0.695173 -2.971644  ... -0.203270 -0.326140  1.509239
272521 -6.783964 -15.415385  0.465512  ... -0.475126 -6.389132  2.249964
274382 -5.748879   0.721743 -1.076274  ...  2.493224  0.880395 -0.130436
274475 -0.055178   0.277831 -1.745854  ...  0.190877  0.473211  0.719400
275992  3.790880  -1.155595 -0.063434  ...  0.033804 -0.315105  0.575520
276071 -1.082511   0.117200 -0.140927  ...  0.037438  0.288253  0.831939
276864 -0.922038  -2.149930 -2.027474  ...  0.650196 -0.870779  0.504849
279863 -0.882850   0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170   0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739   1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002   1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
281674  0.223050  -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28  Amount
3333    0.099131 -0.418417  0.227380  0.153671 -0.010031  0.011484    1.29
160382  0.061540  0.239676  0.026430  0.087697  0.046768  0.184859    0.77
70013   0.007058  0.361068 -0.119296  0.068027  0.247068  0.102098   14.78
90116  -0.029448  1.081649  0.264313  0.948868 -0.047364  0.022200   92.75
170187  0.339380 -0.045770 -0.574834 -0.244093  0.065521 -0.027012   34.00
203052 -0.340061  0.211856 -0.088970  0.627522  0.323029  0.228739    6.30
91339   0.263992  0.648407 -1.555963 -0.051461  0.260336  0.144874    1.78
14249  -0.001467  0.653088  0.153489 -0.431013  0.060560  0.072306  161.00
265572 -0.120413 -0.961224 -0.533422  0.648383  0.425338  0.210717   11.50
198655  0.152492 -0.908893 -1.544044  0.457261  0.052410  0.309467   69.00
252116  0.197927 -0.802519 -0.023514 -0.534939 -0.007915 -0.055990    9.99
284432 -0.054270 -0.219004  0.378141 -0.522403  0.031119  0.018112   20.00
283756 -0.114117 -1.108812  0.570810  0.291358  0.027568  0.090561    0.99
164240 -0.055263  0.085465 -0.110236 -0.783096  0.034695 -0.019311  173.36
248204  0.015086 -0.471670 -0.479300  0.150514  0.246179  0.082778    3.59
238656 -0.041968 -0.990802 -0.381438  0.163006 -0.086065 -0.066953    1.50
132548 -0.177121 -0.445057  0.381650  0.013036  0.047328  0.023282   18.74
77803  -0.042398  1.070261  0.316087  1.111747 -0.039547  0.020914   29.95
113173 -0.173510 -0.226960  0.520231  0.039531  0.060128  0.004777    2.50
281003  0.119200 -0.158691 -0.754186 -0.633851  0.130950  0.108789    9.99
2562   -0.254771  0.715359  0.027097 -0.859451  0.238820 -0.010525    1.00
63630  -0.176210 -0.851950  0.237531 -0.115390 -0.617952 -0.004902   36.72
94038  -0.479681  0.431559  0.312501 -0.725244 -0.000490  0.122048  500.00
203758 -0.091886  0.190077  0.471319  0.697314 -0.118617 -0.093561    0.76
122123 -0.238379  0.090445  0.082495  0.258008  0.135791 -0.036795   19.73
205169  0.298193  0.401871 -0.215014  0.177109 -0.060286 -0.027815   16.00
108628  0.086784  0.057815 -0.163856 -0.632768 -1.170207 -0.217535    3.74
137972  0.019541  0.153682 -0.117809 -0.432899  0.004618  0.058330  254.40
268741 -0.177767 -0.049658 -0.058596  0.091906  0.633772  0.282695    0.77
96805   0.227519  0.012152 -0.195922  0.098703  0.230553  0.101663   92.68
...          ...       ...       ...       ...       ...       ...     ...
251891  0.043414 -0.242380  0.171098 -0.002601 -0.026667  0.005238    7.06
251904 -0.184233 -0.284091  0.493467  0.732329  0.675067  0.337076   94.82
252124 -0.354639 -0.701492 -0.030973  0.034070  0.573393  0.294686    0.77
252774  0.192444 -0.698588  0.025003  0.514968  0.378105 -0.053133    0.77
254344  0.484108  0.359637 -0.435972 -0.248480  0.021527  0.109192  187.11
254395 -0.370157 -0.026012  0.491954  0.234576 -0.279788 -0.331933    7.59
255403 -0.080868 -0.964310  0.338568  0.068630  0.481588  0.268226    4.97
255556 -0.286080 -1.153575 -0.035571  0.559628  0.409446  0.221048    0.77
258403  0.848177 -0.269916 -1.095060 -0.710905  0.565846 -1.034107  296.00
261056 -0.217989 -1.042657  0.314389  0.543244  0.233851  0.119603   45.51
261473  0.258148  0.061901 -0.354180 -1.152671 -0.736073  0.733703    4.90
261925  0.199568  0.146868  0.163602 -0.624085 -1.333100  0.428634  156.00
262560 -0.180409 -0.523271  0.645054  0.246466  0.902675  0.473571    4.69
262826 -0.090358 -0.742802 -0.312361  0.502575  0.821390  0.372379    0.77
263080 -0.245076  0.460049  0.920281 -0.216586 -0.026219 -0.025001    1.00
263274  0.033746 -0.756170 -0.008172  0.532772  0.663970  0.192067    0.77
263324  0.199119  0.035206  0.012159  0.601658  0.137468 -0.171397  127.14
263877 -0.479224 -0.326638 -0.156939  0.113807  0.354124  0.287592    0.38
268375 -0.215966 -0.245727  0.893041  0.865758  0.854657 -0.964482   39.98
272521  1.670508  0.140450  0.162147  1.207731  1.268958  0.097538   12.31
274382  2.241471  0.665346 -1.890041 -0.120803  0.073269  0.583799    0.00
274475  0.122458 -0.255650 -0.619259 -0.484280  0.683535  0.443299   39.90
275992  0.490842  0.756502 -0.142685 -0.602777  0.508712 -0.091646  634.30
276071  0.142007  0.592615 -0.196143 -0.136676  0.020182 -0.015470   19.95
276864  0.137994  0.368275  0.103137 -0.414209  0.454982  0.096711  349.08
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53

[984 rows x 30 columns]
3333      0
160382    0
70013     0
90116     0
170187    0
203052    0
91339     0
14249     0
265572    0
198655    0
252116    0
284432    0
283756    0
164240    0
248204    0
238656    0
132548    0
77803     0
113173    0
281003    0
2562      0
63630     0
94038     0
203758    0
122123    0
205169    0
108628    0
137972    0
268741    0
96805     0
         ..
251891    1
251904    1
252124    1
252774    1
254344    1
254395    1
255403    1
255556    1
258403    1
261056    1
261473    1
261925    1
262560    1
262826    1
263080    1
263274    1
263324    1
263877    1
268375    1
272521    1
274382    1
274475    1
275992    1
276071    1
276864    1
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

In [37]:
#training and fitting the model
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [38]:
L=LogisticRegression()
L.fit(x_train,y_train)

C:\Users\User\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [40]:
y_pred=L.predict(x_train)

In [41]:
#finding accuracy score,classification report
accuracy=accuracy_score(y_train,y_pred)
print(accuracy)
classi=classification_report(y_train,y_pred)
print(classi)

0.9462209302325582
              precision    recall  f1-score   support

           0       0.92      0.97      0.95       342
           1       0.97      0.92      0.95       346

    accuracy                           0.95       688
   macro avg       0.95      0.95      0.95       688
weighted avg       0.95      0.95      0.95       688